### ISSUE TITLE
Handle being called from a subdirectory of the git repo

### ISSUE THREAD

**Issue by thiblahute** [mystor/git-revise#9]
When in a subdir of the git repo I am getting:

```
Traceback (most recent call last):
  File "/home/thiblahute/.local/bin/git-revise", line 10, in <module>
    sys.exit(main())
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/tui.py", line 191, in main
    inner_main(args, repo)
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/tui.py", line 182, in inner_main
    interactive(args, repo, staged, head)
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/tui.py", line 99, in interactive
    todos = edit_todos(repo, todos, msgedit=args.edit)
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/todo.py", line 213, in edit_todos
    """,
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/utils.py", line 90, in run_editor
    path = repo.get_tempdir() / filename
  File "/home/thiblahute/.local/lib/python3.7/site-packages/gitrevise/odb.py", line 223, in get_tempdir
    self._tempdir = TemporaryDirectory(prefix="revise.", dir=str(self.gitdir))
  File "/usr/lib64/python3.7/tempfile.py", line 788, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib64/python3.7/tempfile.py", line 366, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '.git/revise.99am3enc'
```

cd the toplevel dir works just fine.

**Comment by mystor** [comment]
Thanks for catching this! Slipped up when changing where the tempdir is created and accidentally registered it relative to the root, rather than the current working directory. Should be fixed in v0.4.2
